apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: adrianfl95/mysql:latest
        volumeMounts:
          - name: pvc-mysql-config
            mountPath: /data

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: key-list
              key: password-mysql
        ports:
        - containerPort: 3306
          name: mysqldb
      volumes: 
        - name: pvc-mysql-config
          persistentVolumeClaim:
            claimName: pvc-mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
